from alembic import op
import sqlalchemy as sa

revision = '75eb0b70b404'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('label_customers', sa.String(length=64), nullable=True),
    sa.Column('label_products', sa.String(length=64), nullable=True),
    sa.Column('primary_color', sa.String(length=16), nullable=True),
    sa.Column('insight_margin_delta_pp', sa.Float(), nullable=True),
    sa.Column('insight_profitability_delta_pp', sa.Float(), nullable=True),
    sa.Column('insight_expenses_ratio_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_settings_company_id'), ['company_id'], unique=True)

    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('source_module', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_event_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_event_event_date'), ['event_date'], unique=False)

    op.create_table('calendar_user_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_user_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_user_config_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_user_config_user_id'), ['user_id'], unique=True)

    op.create_table('cash_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('opening_amount', sa.Float(), nullable=False),
    sa.Column('cash_day_amount', sa.Float(), nullable=False),
    sa.Column('closing_amount', sa.Float(), nullable=False),
    sa.Column('difference_amount', sa.Float(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_count', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_count_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_count_count_date'), ['count_date'], unique=True)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_parent_id'), ['parent_id'], unique=False)

    op.create_table('company',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('pause_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_slug'), ['slug'], unique=True)

    op.create_table('customer',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_name'), ['name'], unique=False)

    op.create_table('employee',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('inactive_date', sa.Date(), nullable=True),
    sa.Column('default_payment_method', sa.String(length=32), nullable=True),
    sa.Column('contract_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('reference_salary', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_hire_date'), ['hire_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_name'), ['name'], unique=False)

    op.create_table('expense',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('supplier_id', sa.String(length=64), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('expense_type', sa.String(length=32), nullable=True),
    sa.Column('frequency', sa.String(length=32), nullable=True),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_expense_date'), ['expense_date'], unique=False)

    op.create_table('expense_category',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_category_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_category_name'), ['name'], unique=False)

    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('ticket', sa.String(length=32), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('sale_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_gift', sa.Boolean(), nullable=False),
    sa.Column('gift_code', sa.String(length=64), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('discount_general_pct', sa.Float(), nullable=False),
    sa.Column('discount_general_amount', sa.Float(), nullable=False),
    sa.Column('on_account', sa.Boolean(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('due_amount', sa.Float(), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('exchange_return_total', sa.Float(), nullable=True),
    sa.Column('exchange_new_total', sa.Float(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_sale_date'), ['sale_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_ticket'), ['ticket'], unique=True)

    op.create_table('supplier',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('supplier_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('categories_json', sa.Text(), nullable=True),
    sa.Column('invoice_type', sa.String(length=32), nullable=True),
    sa.Column('default_payment_method', sa.String(length=64), nullable=True),
    sa.Column('payment_terms', sa.String(length=64), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('preferred_contact_channel', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_name'), ['name'], unique=False)

    op.create_table('system_meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('permissions_json', sa.Text(), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('internal_code', sa.String(length=64), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('unit_name', sa.String(length=32), nullable=True),
    sa.Column('uses_lots', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('primary_supplier_id', sa.String(length=64), nullable=True),
    sa.Column('primary_supplier_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_internal_code'), ['internal_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_primary_supplier_id'), ['primary_supplier_id'], unique=False)

    op.create_table('sale_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_item_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_item_sale_id'), ['sale_id'], unique=False)

    op.create_table('inventory_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_initial', sa.Float(), nullable=False),
    sa.Column('qty_available', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('supplier_id', sa.String(length=64), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('lot_code', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('origin_sale_ticket', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_lot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_lot_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_lot_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_lot_lot_code'), ['lot_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_lot_origin_sale_ticket'), ['origin_sale_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_lot_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_lot_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_lot_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('inventory_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('sale_ticket', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('qty_delta', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lot.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movement_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_movement_date'), ['movement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_sale_ticket'), ['sale_ticket'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movement_sale_ticket'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_movement_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_lot_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_company_id'))

    op.drop_table('inventory_movement')
    with op.batch_alter_table('inventory_lot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_lot_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_lot_received_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_lot_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_lot_origin_sale_ticket'))
        batch_op.drop_index(batch_op.f('ix_inventory_lot_lot_code'))
        batch_op.drop_index(batch_op.f('ix_inventory_lot_expiration_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_lot_company_id'))

    op.drop_table('inventory_lot')
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_item_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_item_company_id'))

    op.drop_table('sale_item')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_primary_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_internal_code'))
        batch_op.drop_index(batch_op.f('ix_product_company_id'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))
        batch_op.drop_index(batch_op.f('ix_product_barcode'))

    op.drop_table('product')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_company_id'))

    op.drop_table('user')
    op.drop_table('system_meta')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_name'))
        batch_op.drop_index(batch_op.f('ix_supplier_company_id'))

    op.drop_table('supplier')
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_ticket'))
        batch_op.drop_index(batch_op.f('ix_sale_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sale_company_id'))

    op.drop_table('sale')
    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_category_name'))
        batch_op.drop_index(batch_op.f('ix_expense_category_company_id'))

    op.drop_table('expense_category')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expense_company_id'))

    op.drop_table('expense')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_name'))
        batch_op.drop_index(batch_op.f('ix_employee_hire_date'))
        batch_op.drop_index(batch_op.f('ix_employee_company_id'))

    op.drop_table('employee')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_name'))
        batch_op.drop_index(batch_op.f('ix_customer_company_id'))

    op.drop_table('customer')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_slug'))

    op.drop_table('company')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_parent_id'))
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.drop_index(batch_op.f('ix_category_company_id'))

    op.drop_table('category')
    with op.batch_alter_table('cash_count', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_count_count_date'))
        batch_op.drop_index(batch_op.f('ix_cash_count_company_id'))

    op.drop_table('cash_count')
    with op.batch_alter_table('calendar_user_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_user_config_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_user_config_company_id'))

    op.drop_table('calendar_user_config')
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_event_event_date'))
        batch_op.drop_index(batch_op.f('ix_calendar_event_company_id'))

    op.drop_table('calendar_event')
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_settings_company_id'))

    op.drop_table('business_settings')
    # ### end Alembic commands ###
